

# Informations du projet
sonar.projectName=DevSecOps Platform
sonar.projectVersion=1.0

# Sources à analyser
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.test.js

# Java
sonar.java.binaries=backend/target/classes
sonar.java.source=21

# Encodage
sonar.sourceEncoding=UTF-8